//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlavoGonki.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KlavoGonki.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bigdevuatka {
            get {
                object obj = ResourceManager.GetObject("Bigdevuatka", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bimer {
            get {
                object obj = ResourceManager.GetObject("bimer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bimerbig {
            get {
                object obj = ResourceManager.GetObject("Bimerbig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap devyatina {
            get {
                object obj = ResourceManager.GetObject("devyatina", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jopel {
            get {
                object obj = ResourceManager.GetObject("jopel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jopelbig2 {
            get {
                object obj = ResourceManager.GetObject("Jopelbig2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Maskarad1 {
            get {
                object obj = ResourceManager.GetObject("Maskarad1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Maskaradbig {
            get {
                object obj = ResourceManager.GetObject("Maskaradbig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap merin {
            get {
                object obj = ResourceManager.GetObject("merin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Merinbig1 {
            get {
                object obj = ResourceManager.GetObject("Merinbig1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap soundoff1 {
            get {
                object obj = ResourceManager.GetObject("soundoff1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap soundon1 {
            get {
                object obj = ResourceManager.GetObject("soundon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tazik {
            get {
                object obj = ResourceManager.GetObject("tazik", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tazikbig1 {
            get {
                object obj = ResourceManager.GetObject("tazikbig1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Говорят, зло не имеет лица. Действительно, на его лице не отражалось никаких чувств. Ни проблеска сочувствия не было на нем, а ведь боль просто невыносима. Разве он не видит ужас в моих глазах и панику на моем лице? Он спокойно, можно сказать, профессионально выполнял свою грязную работу, а в конце учтиво сказал: &quot;Прополощите рот, пожалуйста&quot;..
        /// </summary>
        internal static string TextFilewithoutEntering1 {
            get {
                return ResourceManager.GetString("TextFilewithoutEntering1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Был только один выход, ибо наши жизни сплелись в слишком запутанный узел гнева и блаженства, чтобы решить все как-нибудь иначе. Доверимся жребию: орел - и мы поженимся, решка - и мы расстанемся навсегда. Монетка была подброшена. Она звякнула, завертелась и остановилась. Орел. Мы уставились на нее с недоумением. Затем, в один голос, мы сказали: &quot;Может, еще разок?&quot;.
        /// </summary>
        internal static string TextFilewithoutEntering2 {
            get {
                return ResourceManager.GetString("TextFilewithoutEntering2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шерстяное одеяло, что ему недавно дали в благотворительном фонде, удобно обнимало его плечи, а ботинки, которые он сегодня нашел в мусорном баке, абсолютно не жали. Уличные огни так приятно согревали душу после всей этой холодящей темноты... Изгиб скамьи в парке казался таким знакомым его натруженной старой спине. &quot;Спасибо тебе, Господи, - подумал он, - жизнь просто восхитительна!&quot;.
        /// </summary>
        internal static string TextFilewithoutEntering3 {
            get {
                return ResourceManager.GetString("TextFilewithoutEntering3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С тех пор, как Риту жестоко убили, Картер сидит у окна. Никакого телевизора, чтения, переписки. Его жизнь - то, что видно через занавески. Ему плевать, кто приносит еду, платит по счетам, он не покидает комнаты. Его жизнь - пробегающие физкультурники, смена времен года, проезжающие автомобили, призрак Риты. Картер не понимает, что в обитых войлоком палатах нет окон..
        /// </summary>
        internal static string TextFilewithoutEntering4 {
            get {
                return ResourceManager.GetString("TextFilewithoutEntering4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы бежите к автобусу на остановке, но перед вами захлопывается дверь, и автобус благополучно уезжает без вас, знайте - это не случайность, и не бестолковый водитель. Это у них такая развлекуха, у водителей. Ни за что бы не поверил, если бы случайно в поезде не услышал разговор двоих шоферов-водителей автобусов. Сейчас, когда водитель и кондуктор привязаны заработком к количеству пассажиров, такое случается реже, но… представьте, какая скука, целый день - закрой двери - открой двери… и тут такая удача - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextFilewithoutEntering5 {
            get {
                return ResourceManager.GetString("TextFilewithoutEntering5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream The_ARTISANS___True_Moment {
            get {
                return ResourceManager.GetStream("The_ARTISANS___True_Moment", resourceCulture);
            }
        }
    }
}
